### ISSUE TITLE
Errors when compiling

### ISSUE THREAD

**Issue by aleza84** [synox/openweathermap-spark-lib#1]
I followed all the instructions and keep getting this errors:

In file included from ../inc/spark_wiring.h:29:0,
from ../inc/spark_wiring_stream.h:36,
from ../inc/spark_wiring_client.h:24,
from ../inc/spark_wiring_tcpclient.h:29,
from HttpClient/HttpClient.h:5,
from HttpClient/HttpClient.cpp:1:
../../core-common-lib/SPARK_Firmware_Driver/inc/config.h:12:2: warning: #warning "Defaulting to Release Build" [-Wcpp]
# warning "Defaulting to Release Build"

^
In file included from ../../core-common-lib/CC3000_Host_Driver/evnt_handler.h:38:0,
from ../inc/spark_wlan.h:33,
from ../inc/main.h:38,
from ../inc/spark_utilities.h:30,
from ../inc/spark_wiring.h:33,
from ../inc/spark_wiring_stream.h:36,
from ../inc/spark_wiring_client.h:24,
from ../inc/spark_wiring_tcpclient.h:29,
from HttpClient/HttpClient.h:5,
from HttpClient/HttpClient.cpp:1:
../../core-common-lib/CC3000_Host_Driver/socket.h:146:0: warning: "fd_set" redefined [enabled by default]
# define fd_set _types_fd_set_cc3000

^
In file included from /opt/gcc_arm/arm-none-eabi/include/stdio.h:47:0,
from ../inc/spark_wiring_print.h:30,
from ../inc/spark_wiring_string.h:33,
from HttpClient/HttpClient.h:4,
from HttpClient/HttpClient.cpp:1:
/opt/gcc_arm/arm-none-eabi/include/sys/types.h:256:0: note: this is the location of the previous definition
# define fd_set _types_fd_set

^
In file included from ../../core-common-lib/CC3000_Host_Driver/evnt_handler.h:38:0,
from ../inc/spark_wlan.h:33,
from ../inc/main.h:38,
from ../inc/spark_utilities.h:30,
from ../inc/spark_wiring.h:33,
from ../inc/spark_wiring_stream.h:36,
from ../inc/spark_wiring_client.h:24,
from ../inc/spark_wiring_tcpclient.h:29,
from HttpClient/HttpClient.h:5,
from HttpClient/HttpClient.cpp:1:
../../core-common-lib/CC3000_Host_Driver/socket.h:162:0: warning: "FD_SET" redefined [enabled by default]
# define FD_SET(fd, fdsetp) __FD_SET (fd, fdsetp)

^
In file included from /opt/gcc_arm/arm-none-eabi/include/stdio.h:47:0,
from ../inc/spark_wiring_print.h:30,
from ../inc/spark_wiring_string.h:33,
from HttpClient/HttpClient.h:4,
from HttpClient/HttpClient.cpp:1:
/opt/gcc_arm/arm-none-eabi/include/sys/types.h:258:0: note: this is the location of the previous definition
# define FD_SET(n, p) ((p)->fds_bits[(n)/NFDBITS] |= (1L << ((n) % NFDBITS)))

^
In file included from ../../core-common-lib/CC3000_Host_Driver/evnt_handler.h:38:0,
from ../inc/spark_wlan.h:33,
from ../inc/main.h:38,
from ../inc/spark_utilities.h:30,
from ../inc/spark_wiring.h:33,
from ../inc/spark_wiring_stream.h:36,
from ../inc/spark_wiring_client.h:24,
from ../inc/spark_wiring_tcpclient.h:29,
from HttpClient/HttpClient.h:5,
from HttpClient/HttpClient.cpp:1:
../../core-common-lib/CC3000_Host_Driver/socket.h:163:0: warning: "FD_CLR" redefined [enabled by default]
# define FD_CLR(fd, fdsetp) __FD_CLR (fd, fdsetp)

^
In file included from /opt/gcc_arm/arm-none-eabi/include/stdio.h:47:0,
from ../inc/spark_wiring_print.h:30,
from ../inc/spark_wiring_string.h:33,
from HttpClient/HttpClient.h:4,
from HttpClient/HttpClient.cpp:1:
/opt/gcc_arm/arm-none-eabi/include/sys/types.h:259:0: note: this is the location of the previous definition
# define FD_CLR(n, p) ((p)->fds_bits[(n)/NFDBITS] &= ~(1L << ((n) % NFDBITS)))

^
In file included from ../../core-common-lib/CC3000_Host_Driver/evnt_handler.h:38:0,
from ../inc/spark_wlan.h:33,
from ../inc/main.h:38,
from ../inc/spark_utilities.h:30,
from ../inc/spark_wiring.h:33,
from ../inc/spark_wiring_stream.h:36,
from ../inc/spark_wiring_client.h:24,
from ../inc/spark_wiring_tcpclient.h:29,
from HttpClient/HttpClient.h:5,
from HttpClient/HttpClient.cpp:1:
../../core-common-lib/CC3000_Host_Driver/socket.h:164:0: warning: "FD_ISSET" redefined [enabled by default]
# define FD_ISSET(fd, fdsetp) __FD_ISSET (fd, fdsetp)

^
In file included from /opt/gcc_arm/arm-none-eabi/include/stdio.h:47:0,
from ../inc/spark_wiring_print.h:30,
from ../inc/spark_wiring_string.h:33,
from HttpClient/HttpClient.h:4,
from HttpClient/HttpClient.cpp:1:
/opt/gcc_arm/arm-none-eabi/include/sys/types.h:260:0: note: this is the location of the previous definition
# define FD_ISSET(n, p) ((p)->fds_bits[(n)/NFDBITS] & (1L << ((n) % NFDBITS)))

^
In file included from ../../core-common-lib/CC3000_Host_Driver/evnt_handler.h:38:0,
from ../inc/spark_wlan.h:33,
from ../inc/main.h:38,
from ../inc/spark_utilities.h:30,
from ../inc/spark_wiring.h:33,
from ../inc/spark_wiring_stream.h:36,
from ../inc/spark_wiring_client.h:24,
from ../inc/spark_wiring_tcpclient.h:29,
from HttpClient/HttpClient.h:5,
from HttpClient/HttpClient.cpp:1:
../../core-common-lib/CC3000_Host_Driver/socket.h:165:0: warning: "FD_ZERO" redefined [enabled by default]
# define FD_ZERO(fdsetp) __FD_ZERO (fdsetp)

^
In file included from /opt/gcc_arm/arm-none-eabi/include/stdio.h:47:0,
from ../inc/spark_wiring_print.h:30,
from ../inc/spark_wiring_string.h:33,
from HttpClient/HttpClient.h:4,
from HttpClient/HttpClient.cpp:1:
/opt/gcc_arm/arm-none-eabi/include/sys/types.h:261:0: note: this is the location of the previous definition
# define FD_ZERO(p) (**extension** (void)({ \

^
In file included from ../inc/spark_wiring.h:29:0,
from ../inc/application.h:29,
from openweathermap.h:10,
from openweathermap.cpp:1:
../../core-common-lib/SPARK_Firmware_Driver/inc/config.h:12:2: warning: #warning "Defaulting to Release Build" [-Wcpp]
# warning "Defaulting to Release Build"

^
In file included from openweathermap.cpp:1:0:
openweathermap.h:11:24: fatal error: JsonParser.h: No such file or directory
# include "JsonParser.h"

^
compilation terminated.
make: **\* [openweathermap.o] Error 1

Any idea what this might be?

**Comment by synox** [comment]
Arduino json parser released a new version with a new api. You have to use an older version because this code was not yet updated.

**Comment by aleza84** [comment]
Thanks a lot, got any idea which version of arduinoJson did you used?

**Comment by synox** [comment]
try https://github.com/bblanchon/ArduinoJson/releases/tag/v1.2

**Comment by Sherkann** [comment]
Hello 
I am new to programming with sparkcore and I find this project very interesting, but I have the same problem when the compilation is terminated. Have you succeeds in getting the weather values ? Thank you in advance

**Comment by synox** [comment]
you should rather use the web-hook used in the project https://github.com/pkourany/RGBPongClock rather than this library. There it is much easier. There you just need to strip of the stuff you don't need. Good luck. 

(I will rewrite this library in the future to also use the web-hook. I am just too busy right now. )

**Comment by Sherkann** [comment]
Hello Synox
Thank you very much for you quick reply.
I'm going to try with this web-hook 
I 'll let you know if it works

**Comment by Sherkann** [comment]
It's so hard for me, I continue to seek hoping for a quick update in your library ;-/
